name: Production Deployment from Release Branch

on:
  push:
    branches:
      - release/*   # triggers on any release branch

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install dependencies & build
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      # Step 4: Authenticate GCP
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 5: Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'

      # Step 6: Set IMAGE & SAFE_TAG
      - name: Set image tag variables
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SAFE_TAG=${BRANCH_NAME//\//-}
          IMAGE=${{ secrets.GCP_GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservicequiz/nodejs-app:$SAFE_TAG
          echo "SAFE_TAG=$SAFE_TAG" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Step 7: Upload build artifacts to GCS
      - name: Upload build artifacts to GCS
        run: |
          BUILD_DIR="dist"
          if [ -d "$BUILD_DIR" ]; then
            gsutil -m cp -r $BUILD_DIR/* gs://${{ secrets.GCS_BUCKET_NAME }}/nodejs-app/${{ env.SAFE_TAG }}/
          else
            echo "$BUILD_DIR folder not found!"
            exit 1
          fi

      # Step 8: Build Docker Image
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE }} .

      # Step 9: Trivy Scan
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: '0'
          ignore-unfixed: true

      # Step 10: Push Docker image to GCR
      - name: Push Docker image
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_GCR_REGION }}-docker.pkg.dev --quiet
          docker push ${{ env.IMAGE }}

      # Step 11: Update Helm values-prod.yaml
      - name: Update Helm values-prod.yaml
        run: |
          git clone https://x-access-token:${{ secrets.HELM_REPO_GITHUB_TOKEN }}@github.com/mokadi-suryaprasad/helm-nodejs-app.git
          cd helm-nodejs-app
          sed -i "s#tag:.*#tag: ${{ env.SAFE_TAG }}#g" values-prod.yaml
          sed -i "s#repository:.*#repository: ${{ secrets.GCP_GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservicequiz/nodejs-app#g" values-prod.yaml

      # Step 12: Commit & Push Helm changes
      - name: Commit & Push Helm changes
        run: |
          cd helm-nodejs-app
          git config user.name "M Surya Prasad"
          git config user.email "mspr9773@gmail.com"
          git add values-prod.yaml
          git commit -m "Update prod image tag to ${{ env.SAFE_TAG }}" || echo "No changes to commit"
          git push origin main
