name: Staging CI

on:
  push:
    branches:
      - pre-prod

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload build artifacts to GCS
        run: |
          gsutil -m cp -r build/* gs://${{ secrets.GCS_BUCKET_NAME }}/nodejs-app/${{ github.sha }}/

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.GCP_GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservicequiz/nodejs-app:staging-${{ github.sha }}
          docker build -t $IMAGE .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.GCP_GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservicequiz/nodejs-app:staging-${{ github.sha }}
          format: table
          exit-code: '0'
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_GCR_REGION }}-docker.pkg.dev --quiet
          docker push ${{ secrets.GCP_GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservicequiz/nodejs-app:staging-${{ github.sha }}

      - name: Run OWASP ZAP scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://your-staging-app-url'  # Replace with actual URL
          cmd_options: '-r zap_report.html'

      - name: Upload OWASP ZAP report to GCS
        run: |
          gsutil cp zap_report.html gs://${{ secrets.GCS_BUCKET_NAME }}/nodejs-app/zap_reports/zap_report-${{ github.sha }}.html

      - name: Update Helm values-staging.yaml
        run: |
          git clone https://x-access-token:${{ secrets.HELM_REPO_GITHUB_TOKEN }}@github.com/mokadi-suryaprasad/helm-nodejs-app.git
          cd helm-nodejs-app
          sed -i "s#tag:.*#tag: staging-${{ github.sha }}#g" values-staging.yaml

      - name: Commit & Push Helm changes
        run: |
          cd helm-nodejs-app
          git config user.name "M Surya Prasad"
          git config user.email "mspr9773@gmail.com"
          git add values-staging.yaml
          git commit -m "Update staging image tag to staging-${{ github.sha }}" || echo "No changes to commit"
          git push origin main
